### ISSUE TITLE
Reduce CAP, add GCI instead

### ISSUE THREAD

**Issue by Frosties82** [Frosties82/RedSnow#52]
Instead of having several CAPs roaming around, remove them and add GCIs.
They will launch where needed.

**Comment by thebgpikester** [comment]
Ideally, (I) would like to remove CAP and have the odd sweep instead. I think the EWR respawning needs to be connected to this too.
The gameplay goal would be forcing a bit of a reactionary and realistic delay to an incursion. keeping a 24/7 patrol up isn't a usual or easy conventional usage of CAP, nations tend to put in a 5 minute QRA. It would give the strikers a bit more opportunity, reduce server load and make some CPU room for more attack flights and possible fighter sweeps.
There's a different feeling from a naked RWR when a "29" suddenly pops up, rather than spawning in and seeing the usual ones in place that are always there.

**Comment by Frosties82** [comment]
Fully agree :)

**Comment by Frosties82** [comment]
GCI is operational
